server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
#    active: dev
  data:
    redis:
      host: common-redis-dev.magestack.cn
      port: 19389
      password: "Sm9sVXBOYJjI030b5tz0trjpzvZzRhtZmEbv0uOImcD1wEDOPfeaqNU4PxHob/Wp"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: short-link-admin
#          uri: lb://short-link-admin/api/shortlink/admin/**
#          predicates:
#            - Path=/api/shortlink/admin/**
#          filters:
#            - name: TokenValidate
#              args:
#                whitePathList:
#                  - /api/shortlink/admin/v1/user/login
#                  - /api/shortlink/admin/v1/user/has-username
#
#        - id: short-link-project
#          uri: lb://short-link-project/api/shortlink/**
#          predicates:
#            - Path=/api/shortlink/**
#          filters:
#            - name: TokenValidate