spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin/api/shortlink/admin/**
          predicates:
            - Path=/api/shortlink/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/shortlink/admin/v1/user/login
                  - /api/shortlink/admin/v1/user/has-username
                  - /api/shortlink/admin/v1/user

        - id: short-link-project
          uri: lb://short-link-project/api/shortlink/**
          predicates:
            - Path=/api/shortlink/**
          filters:
            - name: TokenValidate